### PR TITLE
Added hooks / middleware for channels

### PR DESCRIPTION
**Pull request by bminer**
Implementation of hooks as described in #12.  This implementation has **NOT** yet been tested in any way.

Feedback is welcome!

### CODE REVIEW

**Comment by daniandl** [comment]
Thanks for adding this, code looks good to me 👍 
Will try to get around testing this soon

**Comment by bminer** [comment]
Likewise. This is fairly low priority for me personally, but I think it will be a good addition to the lib. Thanks for the suggestion and your help!

**Comment by bminer** [comment]
@daniandl - Did you happen to test any of this code? Thanks!

**Comment by daniandl** [comment]
> @daniandl - Did you happen to test any of this code? Thanks!

Unfortunately not, I have been swamped with work and our stack has moved away from this library since then.

**Pull request merged**
